# nixpacks.toml (en la RAÃZ del repo)

[phases.setup]
# Pinea el snapshot de nixpkgs para obtener un Node 22.x moderno (>=22.12)
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"
nixPkgs = ["nodejs_22"]

[variables]
NIXPACKS_NODE_VERSION = "22"
